spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: absence-service
          uri: lb://ABSENCE-SERVICE
          predicates:
            - Path=/api/absences/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/manage/**
          filters:
            - AuthenticationFilter
        - id: offre-stage
          uri: lb://OFFRE-STAGE
          predicates:
            - Path=/api/stage/**
          filters:
            - AuthenticationFilter
        - id: stagaire-service
          uri: lb://STAGAIRE-SERVICE
          predicates:
            - Path=/api/stagaires/**
          filters:
            - AuthenticationFilter
        - id: administration-service
          uri: lb://ADMINISTRATION-SERVICE
          predicates:
            - Path=/api/administration/**
          filters:
            - AuthenticationFilter
        - id: employee-management
          uri: lb://EMPLOYEE-MANAGEMENT
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
