
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/stagiaire/**
          filters:
            - AuthenticationFilter


        - id: offre-stage
          uri: lb://OFFRE-STAGE
          predicates:
            - Path=/api/stage/**
          filters:
            - AuthenticationFilter

        - id: employee-management
          uri: lb://EMPLOYEE-MANAGEMENT
          predicates:
#            - Path=/auth/**
            - Path=/api/**
#            - Path=/api/account/**
          filters:
            - AuthenticationFilter

  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

